# Generated by Django 5.2.1 on 2025-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_hotspot_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
