# Generated by Django 5.2.1 on 2025-07-26 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_hotspot_current_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='channel',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
