# Generated by Django 5.2.1 on 2025-06-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotspots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_used', models.PositiveIntegerField(default=0, help_text='Data used in MB')),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='hotspots.hotspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Usage',
                'verbose_name_plural': 'Daily Usage',
                'ordering': ['-date'],
                'unique_together': {('user', 'hotspot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissions_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('reseller', models.ForeignKey(limit_choices_to={'user_type__in': [1, 2]}, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Record',
                'verbose_name_plural': 'Revenue Records',
                'ordering': ['-date'],
                'unique_together': {('reseller', 'date')},
            },
        ),
    ]
